export const AGENDA_LIST_REQUEST = 'AGENDA_LIST_REQUEST'
export const AGENDA_LIST_SUCCESS = 'AGENDA_LIST_SUCCESS'
export const AGENDA_LIST_FAIL    = 'AGENDA_LIST_FAIL'

export const AGENDA_FILTER_BY_USER_LIST_REQUEST = 'AGENDA_FILTER_BY_USER_LIST_REQUEST'
export const AGENDA_FILTER_BY_USER_LIST_SUCCESS = 'AGENDA_FILTER_BY_USER_LIST_SUCCESS'
export const AGENDA_FILTER_BY_USER_LIST_FAIL    = 'AGENDA_FILTER_BY_USER_LIST_FAIL'

export const AGENDA_SINGLE_REQUEST = 'AGENDA_SINGLE_REQUEST'
export const AGENDA_SINGLE_SUCCESS = 'AGENDA_SINGLE_SUCCESS'
export const AGENDA_SINGLE_FAIL    = 'AGENDA_SINGLE_FAIL'

export const AGENDA_ADD_REQUEST =    'AGENDA_ADD_REQUEST'
export const AGENDA_ADD_SUCCESS =    'AGENDA_ADD_SUCCESS'
export const AGENDA_ADD_FAIL    =    'AGENDA_ADD_FAIL'

export const AGENDA_UPDATE_REQUEST = 'AGENDA_UPDATE_REQUEST'
export const AGENDA_UPDATE_SUCCESS = 'AGENDA_UPDATE_SUCCESS'
export const AGENDA_UPDATE_FAIL    = 'AGENDA_UPDATE_FAIL'

export const AGENDA_DELETE_REQUEST = 'AGENDA_DELETE_REQUEST'
export const AGENDA_DELETE_SUCCESS = 'AGENDA_DELETE_SUCCESS'
export const AGENDA_DELETE_FAIL    = 'AGENDA_DELETE_FAIL'