export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS'
export const COURSE_LIST_FAIL    = 'COURSE_LIST_FAIL'

export const COURSE_FILTER_BY_USER_LIST_REQUEST = 'COURSE_FILTER_BY_USER_LIST_REQUEST'
export const COURSE_FILTER_BY_USER_LIST_SUCCESS = 'COURSE_FILTER_BY_USER_LIST_SUCCESS'
export const COURSE_FILTER_BY_USER_LIST_FAIL    = 'COURSE_FILTER_BY_USER_LIST_FAIL'

export const COURSE_SINGLE_REQUEST = 'COURSE_SINGLE_REQUEST'
export const COURSE_SINGLE_SUCCESS = 'COURSE_SINGLE_SUCCESS'
export const COURSE_SINGLE_FAIL    = 'COURSE_SINGLE_FAIL'

export const COURSE_ADD_REQUEST =    'COURSE_ADD_REQUEST'
export const COURSE_ADD_SUCCESS =    'COURSE_ADD_SUCCESS'
export const COURSE_ADD_FAIL    =    'COURSE_ADD_FAIL'

export const COURSE_UPDATE_REQUEST = 'COURSE_UPDATE_REQUEST'
export const COURSE_UPDATE_SUCCESS = 'COURSE_UPDATE_SUCCESS'
export const COURSE_UPDATE_FAIL    = 'COURSE_UPDATE_FAIL'

export const COURSE_DELETE_REQUEST = 'COURSE_DELETE_REQUEST'
export const COURSE_DELETE_SUCCESS = 'COURSE_DELETE_SUCCESS'
export const COURSE_DELETE_FAIL    = 'COURSE_DELETE_FAIL'